"""empty message

Revision ID: 057ac402cce3
Revises: c3cea19ef0ce
Create Date: 2023-10-18 13:20:48.542067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '057ac402cce3'
down_revision = 'c3cea19ef0ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brief_news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('author_home_page', sa.String(length=256), nullable=True))
        batch_op.drop_column('authorHomePage')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brief_news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authorHomePage', mysql.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('author_home_page')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
