"""empty message

Revision ID: 40554a08ec26
Revises: 057ac402cce3
Create Date: 2023-10-18 13:31:04.267020

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '40554a08ec26'
down_revision = '057ac402cce3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brief_news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_width', sa.Integer(), nullable=True))
        batch_op.drop_column('cover_weight')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brief_news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_weight', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.drop_column('cover_width')

    # ### end Alembic commands ###
