"""empty message

Revision ID: 47105241d1b2
Revises: f5377bbc353e
Create Date: 2023-10-19 21:27:08.396912

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '47105241d1b2'
down_revision = 'f5377bbc353e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brief_news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover', sa.String(length=256), nullable=True))
        batch_op.drop_column('cover_img')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brief_news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_img', mysql.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('cover')

    # ### end Alembic commands ###
