"""empty message

Revision ID: e155fe598f74
Revises: 47105241d1b2
Create Date: 2023-10-19 21:32:35.719557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e155fe598f74'
down_revision = '47105241d1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brief_news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_time', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('brief_news', schema=None) as batch_op:
        batch_op.drop_column('post_time')

    # ### end Alembic commands ###
